### ISSUE TITLE
SAMTools `1.19`, `1.19.1`, and `1.19.2`

### ISSUE THREAD

**Issue by yashpatel6** [uclahs-cds/docker-SAMtools#14]
SAMtools versions up to `1.19.1` are available on conda

**Comment by sorelfitzgibbon** [comment]
Do we want to wait until `1.19.2` is available on conda since it [fixed a bug](https://github.com/samtools/samtools/releases/tag/1.19.2) introduced in `1.19.1`?

**Comment by kiarod** [comment]
@sorelfitzgibbon seems like they just uploaded 1.19.2 2 hours ago haha so they must have heard you! I can take care of this update :)
